Final 1

diff --git a/bin/repo_cloneall b/bin/repo_cloneall
--- a/bin/repo_cloneall
+++ b/bin/repo_cloneall
@@ -4,10 +4,14 @@
 # from git server listed in MI_HOME/etc/repos.conf.
 # Joyent 2013.
 
-# Set MI_HOME and get lib
+set -o errexit
+set -o pipefail
+set -o nounset
+#set -o xtrace
+
+# Set MI_HOME and source MI_HOME/lib/mibe.inc if exists
 MI_HOME=$(dirname $(cd ${0%/*} && pwd -P));
-source ${MI_HOME}/lib/mibe.inc;
-MI_CURR=$(pwd);
+[[ -s "${MI_HOME}/lib/mibe.inc" ]] && source ${MI_HOME}/lib/mibe.inc || { echo "* ERROR - ${MI_HOME}/lib/mibe.inc not found, can't continue."; exit 1; }
 
 # Get git server and repos list
 get_gitserver;
@@ -18,7 +22,6 @@ get_reposlist;
 for i in ${MI_REPOSLIST[@]}; do
 	[[ "${i}" =~ ^# ]] && continue;
 	[[ -d "${i}" ]] && echo "* ${i} already exists, skipping." && continue;
-	echo "* Cloning $i into ${MI_CURR}/${i}..";
-	echo "git clone ${MI_GITSERVER}/${i}.git";
+	echo "* Cloning ${MI_GITSERVER}/$i into ${i}..";
 	git clone ${MI_GITSERVER}/${i}.git
 done
diff --git a/bin/repo_pullall b/bin/repo_pullall
--- a/bin/repo_pullall
+++ b/bin/repo_pullall
@@ -3,12 +3,17 @@
 # git pulls all repositories listed in MI_HOME/etc/repos.list.
 # Joyent 2013.
 
-# Set MI_HOME and get lib
+set -o errexit
+set -o pipefail
+set -o nounset
+#set -o xtrace
+
+# Set MI_HOME and source MI_HOME/lib/mibe.inc if exists
 MI_HOME=$(dirname $(cd ${0%/*} && pwd -P));
-source ${MI_HOME}/lib/mibe.inc;
-MI_CURR=$(pwd);
+[[ -s "${MI_HOME}/lib/mibe.inc" ]] && source ${MI_HOME}/lib/mibe.inc || { echo "* ERROR - ${MI_HOME}/lib/mibe.inc not found, can't continue."; exit 1; }
 
 # Get git server and repos list
+get_gitserver;
 IFS=$'\n'
 get_reposlist;
 
@@ -16,7 +21,7 @@ get_reposlist;
 for i in ${MI_REPOSLIST[@]}; do
 	[[ "${i}" =~ ^# ]] && continue;
 	[[ ! -s "${i}/.git/config" ]] && echo "* ${i} doesn't exist, skipping." && continue;
-	echo "* Pulling $i..";
-	cd ${MI_CURR}/$i && git pull
-	cd ${MI_CURR}
+	echo "* Pulling ${MI_GITSERVER}/$i in $i..";
+	cd $i && git pull
+	cd ..
 done
